### ISSUE TITLE
Request: Add "Chat" to the elements on the author widget

### ISSUE THREAD

**Issue by lordneeko** [mikevasiloff/sp-hover-card#1]
![image](https://user-images.githubusercontent.com/11577533/119001918-6a818380-b95a-11eb-8f1f-c16428e0e860.png)

**Comment by mikevasiloff** [comment]
@lordneeko, per your screenshot you seem to know how to copy & paste the "Send email" button to make a "Chat" button, so that's good.  As for the href to use, assuming a DoD environment, your URL would be:
`"href": "='https://dod.teams.microsoft.us/l/chat/0/0?users=' + @currentField.email"`

**Comment by lordneeko** [comment]
so what I wonder is where is the API docs for that @currentField object? Is there a chance that the "server path" is already in there somewhere so you do not have to hard code it?

Also, this was a screenshot from the auto-hover popup that displays in Outlook

**Comment by lordneeko** [comment]
nvrmnd. forget what I said about the currentItem. The domain for the Teams interface is different than the domain for the SharePoint site.
Adding the chat icon was simple enough though.
![image](https://user-images.githubusercontent.com/11577533/119348074-61e6c100-bc6a-11eb-8ab0-70e83aa844c7.png)
